### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by gilcu2** [ospray/module_mpi#1]
When build with superbuild,  Master of module_mpi and origin/release-2.0.x of Ospray I get:

CMake Error at modules/module_mpi/tutorials/CMakeLists.txt:65 (add_library):
  Cannot find source file:

    /home/reynaldo/src/ospray/apps/ospExamples/ArcballCamera.cpp

**Comment by Twinklebear** [comment]
Hey @gilcu2 , there's been some ongoing updates to the app directory structure in OSPRay that I haven't gotten this module back up to date with. I'll ping you on this issue when it's updated

**Comment by Twinklebear** [comment]
@gilcu2 this looks like it was actually fixed on the devel branch of the module (https://github.com/ospray/module_mpi/tree/devel) , could you try building with that? I just sync'd the master branch with devel as well

**Comment by johguenther** [comment]
Fixed in latest release.
